steps:
  - name: 'python:3.10-slim'
    id: 'Validate'
    entrypoint: 'bash'
    args: ['scripts/validate_dag.sh']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'bash'
    args: ['scripts/deploy_dag.sh']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger'
    entrypoint: 'bash'
    args: ['scripts/trigger_dag.sh']

# ĐƯA RA NGOÀI: serviceAccount nằm cùng cấp với steps
serviceAccount: 'projects/duynp20-project/serviceAccounts/cloudbuil-deployer@duynp20-project.iam.gserviceaccount.com'

# GIỮ LẠI: logging vẫn nằm trong options
options:
  logging: CLOUD_LOGGING_ONLY
